version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py collectstatic --noinput
      - python manage.py migrate
  post_build:
    commands:
      - gunicorn Sorelle-Tchie-Software-Engineer.wsgi:application --bind 0.0.0.0:8000
      - echo "Build completed!"

artifacts:
  baseDirectory: /mnt/c/Users/sorel/sorelletchie-software-engineer/portfolio/static
  files:
    - '**/*'
  discardPaths: no
